INSERT INTO PROFESSOR(PROFESSOR_ID,PROFESSOR_ADDRESS,PROFESSOR_AGE,PROFESSOR_NAME)
VALUES (1,'Dapoli','70','Popat Misal');

INSERT INTO PROFESSOR(PROFESSOR_ID,PROFESSOR_ADDRESS,PROFESSOR_AGE,PROFESSOR_NAME)
VALUES (2,'Dapoli','45','Dhelakle');

INSERT INTO PROFESSOR(PROFESSOR_ID,PROFESSOR_ADDRESS,PROFESSOR_AGE,PROFESSOR_NAME)
VALUES (3,'Dapoli','48','Mali');


INSERT INTO SUBJECTS(SUBJECT_ID,SUBJECT_DURATION,SUBJECT_NAME,SUBJECT_ROOM_NUMBER,SUBJECT_TIMING)
VALUES (101,'1hr','Math-1','200','8am - 9am');

INSERT INTO SUBJECTS(SUBJECT_ID,SUBJECT_DURATION,SUBJECT_NAME,SUBJECT_ROOM_NUMBER,SUBJECT_TIMING)
VALUES (102,'1hr','Math-2','200','12pm - 1pm');

INSERT INTO SUBJECTS(SUBJECT_ID,SUBJECT_DURATION,SUBJECT_NAME,SUBJECT_ROOM_NUMBER,SUBJECT_TIMING)
VALUES (103,'2hr','Chemistry','200','9.30am - 11.30am');


INSERT INTO PROFESSOR_SUBJECTS(PROFESSOR_ID,SUBJECTS_ID)
VALUES (1,101);

INSERT INTO PROFESSOR_SUBJECTS(PROFESSOR_ID,SUBJECTS_ID)
VALUES (1,102);

INSERT INTO PROFESSOR_SUBJECTS(PROFESSOR_ID,SUBJECTS_ID)
VALUES (2,103);

INSERT INTO PROFESSOR_SUBJECTS(PROFESSOR_ID,SUBJECTS_ID)
VALUES (3,103);