INSERT INTO BOOK(BOOK_ID,BOOK_AUTHOR,BOOK_AUTHOR_NO,BOOK_CATEGORY,BOOK_NAME,BOOK_PAGES,BOOK_PRICE,BOOK_PUBLICATION,BOOK_REGIS_NO)
VALUES (101,'Ram','H128','Sci-Fi','Predestination','500',399,'TimeLine','8129');

INSERT INTO BOOK(BOOK_ID,BOOK_AUTHOR,BOOK_AUTHOR_NO,BOOK_CATEGORY,BOOK_NAME,BOOK_PAGES,BOOK_PRICE,BOOK_PUBLICATION,BOOK_REGIS_NO)
VALUES (102,'Sham','B709','Sci-Fi','Avengers','900',899,'BoxOffice','9211');

INSERT INTO BOOK(BOOK_ID,BOOK_AUTHOR,BOOK_AUTHOR_NO,BOOK_CATEGORY,BOOK_NAME,BOOK_PAGES,BOOK_PRICE,BOOK_PUBLICATION,BOOK_REGIS_NO)
VALUES (103,'Baburav','Z788','Sci-Fi','Eternals','800',699,'Marvel','1109');

INSERT INTO BOOK(BOOK_ID,BOOK_AUTHOR,BOOK_AUTHOR_NO,BOOK_CATEGORY,BOOK_NAME,BOOK_PAGES,BOOK_PRICE,BOOK_PUBLICATION,BOOK_REGIS_NO)
VALUES (104,'Teja','I227','Sci-Fi','Transcendence','1000',1500,'Rok','3130');